export enum EActivityStatus {
  REQUESTED = 'Requested',
  COMPLETED = 'Completed',
  REPORTED = 'Reported',
  ONGOING = 'Ongoing',
  NOTREPORTED = 'Not Reported',
  REJECTEDBYDEAN = 'Rejected by Vice Dean',
  REJECTEDBYCHANCELLOR = 'Rejected by Vice Chancellor',
  REJECTEDBYDEPARTMENT = 'Rejected by Head Department',
  REJECTEDBYSTUDENTGOVERMENT = 'Rejected by Student Government',
  REJECTEDBYSTUDENTCOUNCIL = 'Rejected by Student Council',
  APPROVEDBYDEAN = 'Approved by Vice Dean',
  APPROVEDBYCHANCELLOR = 'Approved by Vice Chancellor',
  APPROVEDBYDEPARTMENT = 'Approved by Head Department',
  APPROVEDBYSTUDENTGOVERMENT = 'Approved by Student Government',
  APPROVEDBYSTUDENTCOUNCIL = 'Approved by Student Council',
}

export enum EActivityStatusTranslation {
  REQUESTED = 'Sedang diajukan',
  COMPLETED = 'Selesai',
  ONGOING = 'Kegiatan Berjalan',
  REPORTED = 'Sudah melaporkan',
  NOTREPORTED = 'Belum melaporkan',
  APPROVED = 'Kegiatan Disetujui',
  REJECTED = 'Kegiatan Ditolak',
  REJECTEDBYDEAN = 'Ditolak oleh Wakil Dekan',
  REJECTEDBYCHANCELLOR = 'Ditolak oleh Wakil Rektor',
  REJECTEDBYDEPARTMENT = 'Ditolak oleh Kaprodi',
  REJECTEDBYSTUDENTGOVERMENT = 'Ditolak oleh BEM',
  REJECTEDBYSTUDENTCOUNCIL = 'Ditolak oleh DEMA',
  APPROVEDBYDEAN = 'Disetujui oleh Wakil Dekan',
  APPROVEDBYCHANCELLOR = 'Disetujui oleh Wakil Rektor',
  APPROVEDBYDEPARTMENT = 'Disetujui oleh Kaprodi',
  APPROVEDBYSTUDENTGOVERMENT = 'Disetujui oleh BEM',
  APPROVEDBYSTUDENTCOUNCIL = 'Disetujui oleh DEMA',
}
