export enum EActivityStatus {
  REQUESTED = 'Requested',
  COMPLETED = 'Completed',
  REPORTED = 'Reported',
  NOTREPORTED = 'Not Reported',
  REJECTEDBYDEAN = 'Rejected by Vice Dean',
  REJECTEDBYCHANCELLOR = 'Rejected by Vice Chancellor',
  REJECTEDBYDEPARTMENT = 'Rejected by Head Department',
  REJECTEDBYSTUDENTGOVERMENT = 'Rejected by Student Government',
  REJECTEDBYSTUDENTCOUNCIL = 'Rejected by Student Council',
  APPROVEDBYDEAN = 'Approved by Vice Dean',
  APPROVEDBYCHANCELLOR = 'Approved by Vice Chancellor',
  APPROVEDBYDEPARTMENT = 'Approved by Head Department',
  APPROVEDBYSTUDENTGOVERMENT = 'Approved by Student Government',
  APPROVEDBYSTUDENTCOUNCIL = 'Approved by Student Council',
  REVISIONBYDEAN = 'Revision oleh Wakil Dekan',
  REVISIONBYCHANCELLOR = 'Revision oleh Wakil Rektor',
  REVISIONBYDEPARTMENT = 'Revision oleh Kaprodi',
  REVISIONBYSTUDENTGOVERMENT = 'Revision oleh BEM',
  REVISIONBYSTUDENTCOUNCIL = 'Revision oleh DEMA',
}

export enum EActivityStatusTranslation {
  APPROVED = 'Kegiatan Disetujui',
  REJECTED = 'Kegiatan Ditolak',
  REVISION = 'Revisi',
  ONGOING = 'Kegiatan Berjalan',
  REQUESTED = 'Sedang diajukan',
  COMPLETED = 'Selesai',
  REPORTED = 'Sudah melaporkan',
  NOTREPORTED = 'Belum melaporkan',
  REJECTEDBYDEAN = 'Ditolak oleh Wakil Dekan',
  REJECTEDBYCHANCELLOR = 'Ditolak oleh Wakil Rektor',
  REJECTEDBYDEPARTMENT = 'Ditolak oleh Kaprodi',
  REJECTEDBYSTUDENTGOVERMENT = 'Ditolak oleh BEM',
  REJECTEDBYSTUDENTCOUNCIL = 'Ditolak oleh DEMA',
  APPROVEDBYDEAN = 'Disetujui oleh Wakil Dekan',
  APPROVEDBYCHANCELLOR = 'Disetujui oleh Wakil Rektor',
  APPROVEDBYDEPARTMENT = 'Disetujui oleh Kaprodi',
  APPROVEDBYSTUDENTGOVERMENT = 'Disetujui oleh BEM',
  APPROVEDBYSTUDENTCOUNCIL = 'Disetujui oleh DEMA',
  REVISIONBYDEAN = 'Direvisi oleh Wakil Dekan',
  REVISIONBYCHANCELLOR = 'Direvisi oleh Wakil Rektor',
  REVISIONBYDEPARTMENT = 'Direvisi oleh Kaprodi',
  REVISIONBYSTUDENTGOVERMENT = 'Direvisi oleh BEM',
  REVISIONBYSTUDENTCOUNCIL = 'Direvisi oleh DEMA',
}
